create extension if not exists pgcrypto;

create table if not exists public.gate_qrs (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null default 'Main gate',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  uid uuid not null unique default gen_random_uuid(),
  public_id text not null unique,
  name text not null,
  role text not null default 'staff' check (role in ('teacher', 'staff', 'student')),
  organization text not null default 'university' check (organization in ('university', 'pedcollege', 'medcollege')),
  department text not null default '',
  student_group text not null default '',
  username text not null unique,
  password text not null,
  password_hash text not null default '',
  avatar text not null default '',
  is_vip boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  uid uuid not null unique default gen_random_uuid(),
  username text not null unique,
  password text not null,
  role text not null default 'employee' check (role in ('employee', 'admin', 'owner')),
  organization text check (organization in ('university', 'pedcollege', 'medcollege')),
  employee_id bigint unique references public.employees(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  day smallint not null check (day between 1 and 7),
  subject text not null,
  start_time time not null,
  end_time time not null,
  group_name text not null default ''
);

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  uid uuid not null unique default gen_random_uuid(),
  employee_id bigint not null references public.employees(id) on delete cascade,
  gate_id bigint references public.gate_qrs(id) on delete set null,
  date date not null,
  check_in_time time not null,
  check_out_time time,
  work_duration text not null default '',
  status text not null default 'normal' check (status in ('normal', 'late', 'critical', 'vip', 'excused')),
  details text not null default '',
  is_excused boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint one_attendance_log_per_employee_day unique (employee_id, date)
);

create index if not exists schedules_employee_id_idx on public.schedules(employee_id);
create index if not exists schedules_employee_day_start_idx on public.schedules(employee_id, day, start_time);
create index if not exists users_employee_id_idx on public.users(employee_id);
create index if not exists users_role_idx on public.users(role);
create index if not exists attendance_logs_employee_id_idx on public.attendance_logs(employee_id);
create index if not exists attendance_logs_gate_id_idx on public.attendance_logs(gate_id);
create index if not exists attendance_logs_date_check_in_idx on public.attendance_logs(date desc, check_in_time desc);

insert into public.gate_qrs (code, title, is_active)
values ('BOLASHAQ-MAIN-GATE-01', 'Main gate', true)
on conflict (code) do update
set title = excluded.title,
    is_active = excluded.is_active;
