# Generated by Django 6.0.6 on 2026-06-16 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student')], default='staff', max_length=16)),
                ('organization', models.CharField(choices=[('university', 'University'), ('pedcollege', 'Pedagogical college'), ('medcollege', 'Medical college')], default='university', max_length=32)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('student_group', models.CharField(blank=True, max_length=80)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GateQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='BOLASHAQ-MAIN-GATE-01', max_length=120, unique=True)),
                ('title', models.CharField(default='Main gate', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.CharField(blank=True, max_length=80)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__name', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('work_duration', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('normal', 'On time'), ('late', 'Late'), ('critical', 'Critical'), ('vip', 'VIP'), ('excused', 'Excused')], default='normal', max_length=16)),
                ('details', models.TextField(blank=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='attendance.employee')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.gateqr')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='one_attendance_log_per_employee_day')],
            },
        ),
    ]
