create extension if not exists pgcrypto;

create table if not exists public.attendance_gateqr (
  id bigint generated by default as identity primary key,
  code varchar(120) not null unique default 'BOLASHAQ-MAIN-GATE-01',
  title varchar(160) not null default 'Main gate',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_employee (
  id bigint generated by default as identity primary key,
  uid uuid not null unique default gen_random_uuid(),
  public_id varchar(32) not null unique,
  name varchar(255) not null,
  role varchar(16) not null default 'staff',
  organization varchar(32) not null default 'university',
  department varchar(255) not null default '',
  student_group varchar(80) not null default '',
  username varchar(80) not null unique,
  password_hash varchar(255) not null,
  avatar varchar(200) not null default '',
  is_vip boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_employee_role_check
    check (role in ('teacher', 'staff', 'student')),
  constraint attendance_employee_organization_check
    check (organization in ('university', 'pedcollege', 'medcollege'))
);

create table if not exists public.attendance_schedule (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.attendance_employee(id) on delete cascade,
  day smallint not null,
  subject varchar(255) not null,
  start_time time not null,
  end_time time not null,
  "group" varchar(80) not null default '',
  constraint attendance_schedule_day_check check (day between 1 and 7)
);

create table if not exists public.attendance_attendancelog (
  id bigint generated by default as identity primary key,
  uid uuid not null unique default gen_random_uuid(),
  employee_id bigint not null references public.attendance_employee(id) on delete cascade,
  gate_id bigint references public.attendance_gateqr(id) on delete set null,
  date date not null,
  check_in_time time not null,
  check_out_time time,
  work_duration varchar(80) not null default '',
  status varchar(16) not null default 'normal',
  details text not null default '',
  is_excused boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint one_attendance_log_per_employee_day unique (employee_id, date),
  constraint attendance_attendancelog_status_check
    check (status in ('normal', 'late', 'critical', 'vip', 'excused'))
);

create index if not exists attendance_schedule_employee_id_idx
  on public.attendance_schedule(employee_id);

create index if not exists attendance_schedule_employee_day_start_idx
  on public.attendance_schedule(employee_id, day, start_time);

create index if not exists attendance_attendancelog_employee_id_idx
  on public.attendance_attendancelog(employee_id);

create index if not exists attendance_attendancelog_gate_id_idx
  on public.attendance_attendancelog(gate_id);

create index if not exists attendance_attendancelog_date_check_in_idx
  on public.attendance_attendancelog(date desc, check_in_time desc);

insert into public.attendance_gateqr (code, title, is_active)
values ('BOLASHAQ-MAIN-GATE-01', 'Main gate', true)
on conflict (code) do update
set title = excluded.title,
    is_active = excluded.is_active;
